### ISSUE TITLE
友链 - 千反田

### ISSUE THREAD

**Issue by SukiEva** [SukiEva/SukiEva.github.io#5]
https://blog.sukiu.top/friends/ 

申请友链须知：         
- 原则上只和技术类博客交换，但不包括含有和色情、暴力、政治敏感的网站。
- 不和剽窃、侵权、无诚信的网站交换，优先和具有原创作品的网站交换。 
- 申请请提供：站点名称、站点链接、站点描述、logo或头像（不要设置防盗链）。 
- 排名不分先后，刷新后重排，更新信息后请留

**注意：**
由于使用Gitalk作为评论区，请在回复后在GitHub issue里设置unsubscribe，否则当有新评论时，会被发邮件。

也可以在收到通知邮件时，点击邮件中的 unsubscribe，即可一键忽略当前issue

**Comment by InhamiRei** [comment]
申请友链，
网站图标：https://inhami.com/static/images/taro-48.png，
网站名称：芋圆社区，
网站地址：https://inhami.com/，
网站简介：Hey、小怪兽的个性化社区

**Comment by InhamiRei** [comment]
不知道为啥多了一个逗号，这个是新的友链
网站图标：https://inhami.com/static/images/taro-48.png
网站名称：芋圆社区
网站地址：https://inhami.com/
网站简介：Hey、小怪兽的个性化社区

**Comment by SukiEva** [comment]
> @InhamiRei
> 不知道为啥多了一个逗号，这个是新的友链
> 网站图标：https://inhami.com/static/images/taro-48.png
> 网站名称：芋圆社区
> 网站地址：https://inhami.com/
> 网站简介：Hey、小怪兽的个性化社区

已添加😊

**Comment by NekoMirra** [comment]
申请友链
网站图标：https://msft.vinidc.top/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
网站名称：🌠MSFT软粉乐园🌠
网站地址：https://msft.vinidc.top/
网站简介：Microsoft微软中文社区(UnOfficial)

**Comment by SukiEva** [comment]
> @GoogleSuper
> 申请友链
> 网站图标：https://msft.vinidc.top/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
> 网站名称：🌠MSFT软粉乐园🌠
> 网站地址：https://msft.vinidc.top/
> 网站简介：Microsoft微软中文社区(UnOfficial)

已添加😊，不过未在贵站发现友链页😶‍🌫️

**Comment by NekoMirra** [comment]
这就加上（（（




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月26日(星期三) 下午5:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)





  
@GoogleSuper
 申请友链
 网站图标：https://msft.vinidc.top/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
 网站名称：🌠MSFT软粉乐园🌠
 网站地址：https://msft.vinidc.top/
 网站简介：Microsoft微软中文社区(UnOfficial)
  
已添加😊，不过未在贵站发现友链页😶‍🌫️
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by InhamiRei** [comment]
为啥你们信息要抄送我啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SukiEva/SukiEva.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月26日(星期三) 下午5:32
***@***.***&gt;;
抄送:&nbsp;"Hey ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)





 这就加上（（（ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年1月26日(星期三) 下午5:31 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5) 
 
 
 
 
 
    
 @GoogleSuper 
  申请友链 
  网站图标：https://msft.vinidc.top/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg 
  网站名称：🌠MSFT软粉乐园🌠 
  网站地址：https://msft.vinidc.top/ 
  网站简介：Microsoft微软中文社区(UnOfficial) 
    
 已添加😊，不过未在贵站发现友链页😶‍🌫️ 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you were mentioned.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NekoMirra** [comment]
啊这，什么情况（



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月26日(星期三) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)





 为啥你们信息要抄送我啊 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        &quot;SukiEva/SukiEva.github.io&quot;                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年1月26日(星期三) 下午5:32 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;&quot;Hey ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5) 
 
 
 
 
 
  这就加上（（（  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2022年1月26日(星期三) 下午5:31  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)  
   
   
   
   
   
      
  @GoogleSuper  
   申请友链  
   网站图标：https://msft.vinidc.top/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg  
   网站名称：🌠MSFT软粉乐园🌠  
   网站地址：https://msft.vinidc.top/  
   网站简介：Microsoft微软中文社区(UnOfficial)  
      
  已添加😊，不过未在贵站发现友链页😶‍🌫️  
     
  —  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.   
  You are receiving this because you were mentioned.Message ID: ***@***.***&amp;amp;gt;  
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you were mentioned.Message ID: ***@***.***&amp;gt; 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LanYunDev** [comment]
申请友链
网站图标：https://lanyundev.vercel.app/img/logo.jpg
网站名称：LanYunのBlog
网站地址：https://lanyundev.vercel.app/
网站简介：Share Technology.

**Comment by NekoMirra** [comment]
原来会自动抄送前一位申请者()

共青团中央
***@***.***

中国共青团



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月28日(周五) 晚上11:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)




 
申请友链
 网站图标：https://lanyundev.vercel.app/img/logo.jpg
 网站名称：LanYunのBlog
 网站地址：https://lanyundev.vercel.app/
 网站简介：Share Technology.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by InhamiRei** [comment]
为啥又抄送我了







------------------ 原始邮件 ------------------
发件人: MicroWin ***@***.***&gt;
发送时间: 2022年1月28日 23:49
收件人: SukiEva/SukiEva.github.io ***@***.***&gt;
抄送: InhamiRei ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)





 原来会自动抄送前一位申请者() 
 
 共青团中央 
 ***@***.*** 
 
 中国共青团 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年1月28日(周五) 晚上11:29 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5) 
 
 
 
 
   
 申请友链 
  网站图标：https://lanyundev.vercel.app/img/logo.jpg 
  网站名称：LanYunのBlog 
  网站地址：https://lanyundev.vercel.app/ 
  网站简介：Share Technology. 
   
 &amp;mdash; 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you were mentioned.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SukiEva** [comment]
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 


你们试试把我这个仓库的通知关了，应该是issue自动通知每个参与者

**Comment by NekoMirra** [comment]
啊这
我们不是故意的()













发件人: ***@***.***&gt;
发送时间: 2022年1月29日(周六) 凌晨0:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)




  
@InhamiRei
 为啥又抄送我了
 
------------------ 原始邮件 ------------------
 发件人: MicroWin @.&gt;
 发送时间: 2022年1月28日 23:49
 收件人: SukiEva/SukiEva.github.io @.&gt;
 抄送: InhamiRei @.&gt;, Mention @.&gt;
 主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
 
原来会自动抄送前一位申请者()
 
共青团中央
 @.***
 
中国共青团
 
---原始邮件---
 发件人: @.&amp;gt;
 发送时间: 2022年1月28日(周五) 晚上11:29
 收件人: @.&amp;gt;;
 抄送: @.@.&amp;gt;;
 主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
 
申请友链
 网站图标：https://lanyundev.vercel.app/img/logo.jpg
 网站名称：LanYunのBlog
 网站地址：https://lanyundev.vercel.app/
 网站简介：Share Technology.
 
&amp;mdash;
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you were mentioned.Message ID: @.&amp;gt;
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you were mentioned.Message ID: @.&gt;
  
你们看看能不能把我这个仓库的通知关了，应该是issue自动通知每一个参与的人
  
@InhamiRei
 为啥又抄送我了
 
------------------ 原始邮件 ------------------
 发件人: MicroWin @.&gt;
 发送时间: 2022年1月28日 23:49
 收件人: SukiEva/SukiEva.github.io @.&gt;
 抄送: InhamiRei @.&gt;, Mention @.&gt;
 主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
 
原来会自动抄送前一位申请者()
 
共青团中央
 @.***
 
中国共青团
 
---原始邮件---
 发件人: @.&amp;gt;
 发送时间: 2022年1月28日(周五) 晚上11:29
 收件人: @.&amp;gt;;
 抄送: @.@.&amp;gt;;
 主题: Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
 
申请友链
 网站图标：https://lanyundev.vercel.app/img/logo.jpg
 网站名称：LanYunのBlog
 网站地址：https://lanyundev.vercel.app/
 网站简介：Share Technology.
 
&amp;mdash;
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you were mentioned.Message ID: @.&amp;gt;
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you were mentioned.Message ID: @.&gt;
  
你们试试把我这个仓库的通知关了，应该是issue自动通知每个参与者
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SukiEva** [comment]
点邮件里的 unsubscribe 即可，我也才发现 gitalk 有点问题😂

**Comment by SukiEva** [comment]
> @LanYunDev
> 申请友链
> 网站图标：https://lanyundev.vercel.app/img/logo.jpg
> 网站名称：LanYunのBlog
> 网站地址：https://lanyundev.vercel.app/
> 网站简介：Share Technology.

已添加😊记得退订这个 Issue 的通知，不然会一直收到邮件😂

**Comment by LanYunDev** [comment]
好，确实.

SukiEva ***@***.***>于2022年1月29日 周六下午2:14写道：

**Comment by NekoMirra** [comment]
更新下链接
网站图标：https://msdf.eu.org/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
网站名称：🌠MSFT软粉乐园🌠
网站地址：https://msdf.eu.org
网站简介：软粉交流论坛

**Comment by InhamiRei** [comment]
你这网站都有风险提示啊
而且为啥抄送我啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SukiEva/SukiEva.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月13日(星期天) 中午1:01
***@***.***&gt;;
抄送:&nbsp;"Hey ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)





 
更新下链接
 网站图标：https://msdf.eu.org/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
 网站名称：🌠MSFT软粉乐园🌠
 网站地址：https://msdf.eu.org
 网站简介：软粉交流论坛
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LanYunDev** [comment]
这下应该不会发给我了吧

**Comment by SukiEva** [comment]
> @InhamiRei
> 你这网站都有风险提示啊
> 而且为啥抄送我啊
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "SukiEva/SukiEva.github.io"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年3月13日(星期天) 中午1:01
> ***@***.***&gt;;
> 抄送:&nbsp;"Hey ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
> 
> 
> 
> 
> 
>  
> 更新下链接
>  网站图标：https://msdf.eu.org/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
>  网站名称：🌠MSFT软粉乐园🌠
>  网站地址：https://msdf.eu.org
>  网站简介：软粉交流论坛
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

评论用的github issue，需要点击邮件里的退订，这是github自动抄送的🤣

**Comment by InhamiRei** [comment]
在哪里，我没有看到诶


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SukiEva/SukiEva.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 上午9:15
***@***.***&gt;;
抄送:&nbsp;"Hey ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)





  
@InhamiRei
 你这网站都有风险提示啊
 而且为啥抄送我啊
 
------------------&nbsp;原始邮件&nbsp;------------------
 发件人:                                                                                                                        "SukiEva/SukiEva.github.io"                                                                                    @.&gt;;
 发送时间:&nbsp;2022年3月13日(星期天) 中午1:01
 @.&gt;;
 抄送:&nbsp;"Hey @.@.&gt;;
 主题:&nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
 
更新下链接
 网站图标：https://msdf.eu.org/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
 网站名称：🌠MSFT软粉乐园🌠
 网站地址：https://msdf.eu.org
 网站简介：软粉交流论坛
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you were mentioned.Message ID: @.***&gt;
  
评论用的github issue，需要点击邮件里的退订，这是github自动抄送的🤣
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SukiEva** [comment]
> @InhamiRei
> 在哪里，我没有看到诶
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "SukiEva/SukiEva.github.io"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2022年3月15日(星期二) 上午9:15
> ***@***.***&gt;;
> 抄送:&nbsp;"Hey ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
> 
> 
> 
> 
> 
>   
> @InhamiRei
>  你这网站都有风险提示啊
>  而且为啥抄送我啊
>  
> ------------------&nbsp;原始邮件&nbsp;------------------
>  发件人:                                                                                                                        "SukiEva/SukiEva.github.io"                                                                                    @.&gt;;
>  发送时间:&nbsp;2022年3月13日(星期天) 中午1:01
>  @.&gt;;
>  抄送:&nbsp;"Hey @.@.&gt;;
>  主题:&nbsp;Re: [SukiEva/SukiEva.github.io] 友链 - 千反田 (Issue #5)
>  
> 更新下链接
>  网站图标：https://msdf.eu.org/wp-content/uploads/2022/01/Thumb640679309007-8f949cca-a7e0-3467-ab2c-1a1f9641bbbe.jpg
>  网站名称：🌠MSFT软粉乐园🌠
>  网站地址：https://msdf.eu.org
>  网站简介：软粉交流论坛
>  
> —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  Triage notifications on the go with GitHub Mobile for iOS or Android.
>  You are receiving this because you were mentioned.Message ID: @.***&gt;
>   
> 评论用的github issue，需要点击邮件里的退订，这是github自动抄送的🤣
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

https://github.com/SukiEva/SukiEva.github.io/issues/5 点击右边的 unsubscribe，
抄送邮件里应该有的啊，我这边能看到
如下：
